openapi: 3.0.3
info:
  title: Project Chimera Orchestrator API
  description: Internal API for swarm goal management and HITL adjudication.
  version: 1.0.0
servers:
  - url: http://localhost:3000/v1
paths:
  /goals:
    post:
      summary: Create a new swarm goal
      operationId: createGoal
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                description:
                  type: string
                priority:
                  type: integer
      responses:
        '201':
          description: Goal created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Goal'
  /tasks/{taskId}/adjudicate:
    post:
      summary: Submit Judge adjudication for a task
      operationId: adjudicateTask
      parameters:
        - name: taskId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                confidenceScore:
                  type: number
                comment:
                  type: string
                decision:
                  type: string
                  enum: [APPROVE, REJECT, ASYNC_REVIEW]
      responses:
        '200':
          description: Adjudication recorded
  /hitl/queue:
    get:
      summary: List tasks requiring manual HITL review
      operationId: listHitlTasks
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
components:
  schemas:
    Goal:
      type: object
      properties:
        goalId:
          type: string
          format: uuid
        description:
          type: string
        status:
          type: string
    Task:
      type: object
      properties:
        taskId:
          type: string
          format: uuid
        type:
          type: string
        status:
          type: string
        input:
          type: object
        output:
          type: object
